# -*- coding: utf-8 -*-
"""Events.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCErPHpHTyou36AHK33feCly6nrSV6X0
"""

def has_overlap(cats, preferences):
    if not isinstance(cats, list):
        return False
    return any(c in preferences for c in cats)

def filtering_fallback(catalog_df, n_recommendation, Start_Date, End_Date, environment=None, city=None, budget=None, family_friendly=None, temp_pref=None, event_preference=None):

    base = catalog_df[
        (catalog_df['Start_Date'] <= End_Date) &
        (catalog_df['End_Date'] >= Start_Date)
    ]

    if family_friendly is not None:
        base = base[base['Family_Friendly'] == family_friendly]

    stage_names = ['strict_match', 'relaxed_weather', 'relaxed_budget', 'expanded_city', 'relaxed_event']
    candidates_df = pd.DataFrame()

    for stage_name in stage_names:
        if len(candidates_df) >= n_recommendation:
            break

        remaining = base[~base.index.isin(candidates_df.index)]
        mask = pd.Series(True, index=remaining.index)

        if environment is not None:
            mask &= remaining['Environment'].apply(
                lambda env: env == 'Both' or env in environment
            )

        if city is not None and stage_name not in ['expanded_city', 'relaxed_event']:
            mask &= remaining['City_Key'].isin(city)

        if budget is not None and stage_name in ['strict_match', 'relaxed_weather']:
            mask &= remaining['Price_Range'].isin(budget)

        # Weather: one consistent field (temp_pref) checked against both max/min category columns
        if temp_pref is not None and stage_name == 'strict_match':
            mask &= (
                remaining['Temp_max_Category'].isin(temp_pref) |
                remaining['Temp_min_Category'].isin(temp_pref)
            )

        if event_preference is not None and stage_name != 'relaxed_event':
            mask &= remaining['Categories'].apply(lambda cats: any(e in cats for e in event_preference))

        matches = remaining[mask].copy()
        matches['fallback_stage'] = stage_name
        candidates_df = pd.concat([candidates_df, matches])

    return candidates_df.head(n_recommendation)

def build_visitor_text(visitor_profile):
    activities = ', '.join(visitor_profile.get('Activity_Preferences', []))
    activity_other = visitor_profile.get('Activity_Other', '') or ''
    cuisines = ', '.join(visitor_profile.get('Cuisine_Preferences', []))
    cuisine_other = visitor_profile.get('Cuisine_Other', '') or ''
    crowd_pref = visitor_profile.get('Crowdedness_Preference', '')
    family = visitor_profile.get('Family_Friendly', False)
    environments = ', '.join(visitor_profile.get('Environment', []))
    special_note = visitor_profile.get('special_note', '') or ''

    visitor_text = (
        f"I am interested in {activities}"
        f"{' and ' + activity_other if activity_other else ''} activities. "
        f"I enjoy {cuisines}"
        f"{' and ' + cuisine_other if cuisine_other else ''} food. "
        f"I prefer {environments} settings with a {crowd_pref.lower() if crowd_pref else ''} crowd level. "
        f"{'I am traveling with kids and prefer family-friendly options.' if family else 'I am not traveling with kids.'} "
        f"{special_note}"
    )
    return visitor_text

def compute_similarity(candidates_df, visitor_profile, tfidf_vectorizer, all_event_vectors):
    visitor_text = build_visitor_text(visitor_profile)
    visitor_vector = tfidf_vectorizer.transform([visitor_text])

    candidate_indices = candidates_df.index
    candidate_vectors = all_event_vectors[candidate_indices]

    similarity_scores = cosine_similarity(candidate_vectors, visitor_vector).flatten()

    candidates_df = candidates_df.copy()
    candidates_df['similarity_score'] = similarity_scores
    return candidates_df

def build_recommendation_reason(row, visitor_profile):
    reasons = {
        'strict_match': 'Matches your city, budget, and weather preference',
        'relaxed_weather': 'Matches your city and budget (weather preference relaxed)',
        'relaxed_budget': 'Matches your city (budget relaxed)',
        'expanded_city': 'Recommended from other locations to meet your request',
        'relaxed_event': 'Recommended based on your general preferences',
    }
    reason = reasons.get(row['fallback_stage'], 'Recommended based on your profile')

    extras = []
    if row.get('Family_Friendly') is True:
        extras.append('family-friendly')

    prefs = set(p.lower() for p in visitor_profile.get('Activity_Preferences', []))
    categories = set(c.lower() for c in row['Categories'])
    matched_activities = prefs & categories
    if matched_activities:
        extras.append(f"matches your interest in {', '.join(matched_activities)}")

    if row.get('date_in_range', True):
        extras.append('falls within your trip dates')

    if extras:
        reason += " (" + ", ".join(extras) + ")"

    return reason

def recommend_events(catalog_df, visitor_profile, tfidf_vectorizer, all_event_vectors):
    n_recommendation = visitor_profile['Num_Recommendations']

    # 1. Filter candidates using fallback stages
    candidates_df = filtering_fallback(
        catalog_df,
        n_recommendation=n_recommendation,
        Start_Date=visitor_profile['Trip_Start_Date'],
        End_Date=visitor_profile['Trip_End_Date'],
        environment=visitor_profile.get('Environment'),
        city=visitor_profile.get('City'),
        budget=visitor_profile.get('budget'),
        family_friendly=visitor_profile.get('Family_Friendly'),
        temp_pref=visitor_profile.get('Temp_Pref'),
        event_preference=visitor_profile.get('Event_Preferences')
    )

    # 2. Compute similarity score
    candidates_df = compute_similarity(candidates_df, visitor_profile, tfidf_vectorizer, all_event_vectors)

    # 3. Apply fallback-stage penalty
    stage_penalty = {
        'strict_match': 1.0,
        'relaxed_weather': 0.80,
        'relaxed_budget': 0.75,
        'expanded_city': 0.6,
        'relaxed_event': 0.5
    }
    candidates_df['final_score'] = candidates_df['similarity_score'] * candidates_df['fallback_stage'].map(stage_penalty)

    # 4. Select Top-N
    final_recommendations = candidates_df.sort_values('final_score', ascending=False).head(n_recommendation).copy()

    # 5. Add visitor_id and recommendation reason
    final_recommendations['visitor_id'] = visitor_profile['User_ID']
    final_recommendations['recommendation_reason'] = final_recommendations.apply(
        lambda row: build_recommendation_reason(row, visitor_profile), axis=1
    )

    # 6. Round scoring columns
    final_recommendations[['similarity_score', 'final_score']] = final_recommendations[['similarity_score', 'final_score']].round(3)

    # 7. Select and order required columns
    required_columns = [
        'visitor_id', 'Name', 'Categories', 'Location',
        'Start_Date', 'End_Date', 'Price_Range', 'similarity_score',
        'fallback_stage', 'final_score', 'recommendation_reason', 'Description'
    ]
    final_recommendations = final_recommendations[required_columns].sort_values(
        by='final_score', ascending=False
    ).reset_index(drop=True)

    # 8. Format for FastAPI: convert dates to strings, return a JSON-safe dict
    final_recommendations['Start_Date'] = final_recommendations['Start_Date'].dt.strftime('%Y-%m-%d')
    final_recommendations['End_Date'] = final_recommendations['End_Date'].dt.strftime('%Y-%m-%d')

    records = final_recommendations.to_dict(orient='records')

    return {
        "visitor_id": visitor_profile['User_ID'],
        "num_results": len(records),
        "recommendations": records,
    }

#to run this code you need all_event vectors tfidif and cleaned df